version: '3'
services:
        budwizard:
                build: .
                image: danksolutions/budwizard
                container_name: "budwizard"
                ports:
                        - "9001:9001"