version: '3'
services:
        budwizard:
                image: registry.digitalocean.com/bud-wizard-image-repo/budwizard-test:1.0.5
                container_name: "budwizard"
                ports:
                        - "9001:9001"