name: bud_wizard
description: A grower's tool for maximized yields
author: Dank Solutions

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Another HTTP package.  I'm told this one is better.
  dio: ^3.0.10
  
  # Used for GUID data types (i.e. Primary Keys/Foreign Keys)
  flutter_guid: ^0.1.0

  # Google Fonts; See https://fonts.google.com/ for all available fonts
  google_fonts: ^1.1.1
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

  # Animation related import
  simple_animations: ^2.5.1

  # Tooltip
  simple_tooltip: ^0.1.16

  # Used for JSON Serialization/Deserialization
  json_annotation: ^3.1.1

  # A wonderful package that allows navigation without context
  get: ^3.22.2

  # A carousel slider for images that supports iOS/Android/Web
  carousel_slider: ^2.3.1

  # Charts library - * Requires BSD License * - Research wtf this means
  fl_chart: ^0.12.2

  # Pretty nice loading animation package
  flutter_spinkit: ^4.1.2+1

  # More icons via community
  community_material_icon: ^5.8.55

  # Nice tool for progressively loading images
  progressive_image: ^1.0.1

  # Used for Animations; Handles the action.
  provider: ^4.3.3

dev_dependencies:
  # Used to create a dart file containing environment info (version, app name, etc.) at build time
  build_runner: ^1.0.0
  build_pubspec: ^0.2.0+1

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - budwizard_logo_400x400.png
     - placeholder.jpg
     - cannabis_login.jpg
     - clock.png
     - female.png
     - hermi.png
     - light.png
     - male.png
     - nutrients.png
     - placeholder.jpg
     - seeds.png
     - white-widow.jpg
     - strawberry-cough.jpg
     - panama-red.jpg
     - dark-angel.jpg
     - cotton-candy.jpg
     - black-widow.jpg
     - afghan.jpg
     - assets/grow/img1.jpg
     - assets/grow/img2.jpg
     - assets/grow/img3.jpg
     - assets/grow/img4.jpg
     - assets/grow/img5.jpg
     - assets/grow/img6.jpg
     - assets/grow/img7.jpg
     - assets/grow/img11.jpg
     - assets/grow/img12.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: fonts/Montserrat-Regular.ttf
     - family: MaterialIcons
       fonts:
         - asset: fonts/MaterialIcons-Regular.ttf
      
    
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
